apiVersion: v2
name: discourse
description: Helm chart for deploying the Discourse application and dependencies.
type: application
version: 0.1.0
appVersion: "beta"
keywords:
  - discourse
  - forum
  - ruby
  - rails
home: https://www.discourse.org/
sources:
  - https://github.com/discourse/discourse
maintainers:
  - name: TechOps Team
    email: ops@example.com
