apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discourse.fullname" . }}-sidekiq
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: sidekiq
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      {{- include "discourse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sidekiq
  template:
    metadata:
      labels:
        {{- include "discourse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sidekiq
      {{- with .Values.sidekiq.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "discourse.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sidekiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.sidekiq.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "discourse.fullname" . }}-config
            - secretRef:
                name: {{ include "discourse.fullname" . }}-secrets
            {{- with .Values.sidekiq.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- with .Values.sidekiq.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.sidekiq.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.sidekiq.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.sidekiq.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sidekiq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sidekiq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
