{{- $fullName := include "discourse.fullname" . -}}
{{- $externalSecrets := default dict .Values.externalSecrets }}
{{- range $k, $v := .Values.env }}
{{- if eq $v.type "parameterStore" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $fullName }}-{{ $v.name }}"
  labels:
    {{- include "discourse.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $externalSecrets.refreshInterval | default "1m" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ required "externalSecrets.clusterSecretStoreName is required when using parameterStore env type" $externalSecrets.clusterSecretStoreName }}
  data:
    - secretKey: "{{ $fullName }}-{{ $v.name }}"
      remoteRef:
        key: {{ $v.parameter_name }}
{{- end }}
{{- end }}
