apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discourse.fullname" . }}-web
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "discourse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "discourse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "discourse.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.web.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "discourse.fullname" . }}-config
            - secretRef:
                name: {{ include "discourse.fullname" . }}-secrets
            {{- with .Values.web.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- with .Values.web.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- range $k, $v := .Values.env }}
            - name: {{ $k | quote }}
            {{- if eq $v.type "kv" }}
              value: {{ $v.value | quote }}
            {{- else if eq $v.type "parameterStore" }}
              valueFrom:
                secretKeyRef:
                  name: "{{ include "discourse.fullname" $ }}-{{ $v.name }}"
                  key: "{{ include "discourse.fullname" $ }}-{{ $v.name }}"
            {{- else if eq $v.type "configmapRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $v.name | quote }}
                  key: {{ $v.key | quote }}
            {{- else if eq $v.type "secret" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $v.name | quote }}
                  key: {{ $v.key | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.web.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: shared-tmp
              mountPath: /shared/tmp
            - name: shared-state
              mountPath: /shared/state
          {{- if and .Values.web.livenessProbe.enabled .Values.web.livenessProbe.httpGet.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.httpGet.path }}
              port: {{ .Values.web.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if and .Values.web.readinessProbe.enabled .Values.web.readinessProbe.httpGet.path }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.httpGet.path }}
              port: {{ .Values.web.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: shared-tmp
          emptyDir: {}
        - name: shared-state
          emptyDir: {}
