{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.postgresql.serviceName" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: {{ .Values.postgresql.servicePort }}
      targetPort: postgres
      protocol: TCP
{{- end }}
