apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.fullname" . }}-web
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ default "http" .Values.service.targetPort }}
      protocol: TCP
